### ISSUE TITLE
Vue 3 support

### ISSUE THREAD

**Issue by akhabali** [soundar24/vue-round-slider#9]
It's will be great if a Vue 3 compatible version is provided.

**Comment by soundar24** [comment]
great, I didn't notice this.. Can you please share a [CodeSandbox](https://github.com/soundar24/vue-round-slider#quick-start) demo to reproduce this issue, which might be helpful for me and saves my time.. thanks

**Comment by soundar24** [comment]
Cool.. I just created a demo by myself, hope this is the issue you are facing..

https://codesandbox.io/s/vue-round-slider-issue-with-vue3-ntyfx

**Comment by akhabali** [comment]
Yes, it's the exact same issue

**Comment by wonyongHwang** [comment]
I found a temporary work-around solution.

1. modify import source 
   before :     import  RoundSlider from "vue-round-slider"
   after    :      import { RoundSlider } from "vue-round-slider/src/index2.js"

2. create index2.js which located in (node_modules/vue-round-slider/src/)
     import RoundSlider from "./round-slider.vue";

      // Install the components
      export function install(Vue) {
        Vue.component("round-slider", RoundSlider);
      }
      
      // Expose the components
      export { RoundSlider };
      
      /* -- Plugin definition & Auto-install -- */
      /* You shouldn't have to modify the code below */
      
      // Plugin
      const plugin = { install };
      
      export default plugin;
      
      // Auto-install
      let GlobalVue = null;
      if (typeof window !== "undefined") {
        GlobalVue = window.Vue;
      } else if (typeof global !== "undefined") {
        GlobalVue = global.Vue;
      }
      if (GlobalVue) {
        GlobalVue.use(plugin);
      }
      
3. download compiled css file to node_modules/vue-round-slider/src/
    curl -O https://cdn.jsdelivr.net/npm/round-slider@1.6.1/dist/roundslider.min.css

4. modify css source of round-slider.vue at node_modules/vue-round-slider/src/
   before : <style src='../node_modules/round-slider/dist/roundslider.min.css'></style>
   after    :  <style src='./roundslider.min.css'></style>

hope this work

**Comment by abbjetmus** [comment]
@wonyongHwang Thank you for the tip this workaround works well in Quasar!

**Comment by kalwinskidawid** [comment]
@soundar24 Are you going to upgrade it to Vue3 or rather not ?

**Comment by soundar24** [comment]
@kalwinskidawid I had a look on this, seems the bundling of Vue2 and Vue3 are different so that it won't support on each other versions. The way to handle this is to keep separate repo, or handling in the similar way of vue-demi.

I will check more on this and update in this thread.

**Comment by kalwinskidawid** [comment]
Awesome, thanks @soundar24!

**Comment by kalwinskidawid** [comment]
@soundar24 Any good news? :)

**Comment by ryntap-vujbu6-wUqxyp** [comment]
@soundar24 Is there a plan compatible with vue3?

**Comment by xalteropsx** [comment]
@wonyongHwang 

Uncaught SyntaxError: The requested module '/node_modules/jquery/dist/jquery.js?v=7ea41283' does not provide an export named 'default' (at round-slider.vue:6:8)

**Comment by Artem9989** [comment]
> @wonyongHwang
> 
> Uncaught SyntaxError: The requested module '/node_modules/jquery/dist/jquery.js?v=7ea41283' does not provide an export named 'default' (at round-slider.vue:6:8)

Try to use https://www.npmjs.com/package/vue-three-round-slider , I wanted to create for vue 3 based on this slider while the task is in progress, but you can already use it, only you will have to import like this `import RoundSlider from vue-three-round-slider` 
I'm still just learning to write my components, if I succeed, I will definitely let you know

**Comment by xalteropsx** [comment]
@Artem9989  thank u very very much awesome  i wonder what is this for https://refreshless.com/nouislider/

**Comment by Artem9989** [comment]
> @Artem9989 thank u very very much awesome i wonder what is this for https://refreshless.com/nouislider/

Sorry, I haven't seen this before

**Comment by Artem9989** [comment]
> @Artem9989 thank u very very much awesome i wonder what is this for https://refreshless.com/nouislider/

I fixed the component, now it can be imported by the standard  `import RoundSlider  from vue-three-round-slider`

**Comment by Artem9989** [comment]
@xalteropsx , @wonyongHwang , @ryntap-vujbu6-wUqxyp , @kalwinskidawid  @abbjetmus , @akhabali 
Hello everyone, I have good news, now you can use the package for Vue 3: npm i vue-three-round-slider
You can watch the demo on codesandbox: https://codesandbox.io/s/demo-vue-three-round-slider-yl2ssp
Now all v-model should not cause problems, thank you for your attention.
https://www.npmjs.com/package/vue-three-round-slider

**Comment by Artem9989** [comment]
I removed the binding to my name, because I'm just learning, I had a few problems to figure out how to do it)

**Comment by xalteropsx** [comment]
its fine great work @Artem9989  may god bless u

**Comment by wonyongHwang** [comment]
@Artem9989 That's very good news. Great Works! Thanks a lot~

**Comment by StormerZSha** [comment]
@Artem9989  that's great,thank u
